@moistSensServer_HostAddress = http://localhost:5298

###
POST {{moistSensServer_HostAddress}}/set-humidity/
Content-Type: application/json

{
  "sensorName": "sensor1",
  "humidity": 53
}

###
POST {{moistSensServer_HostAddress}}/set-sensor-description/
Content-Type: application/json

{
  "sensorName": "sensor1",
  "description": "Carrots"
}

###
GET {{moistSensServer_HostAddress}}/humidity-get/
Accept: application/json

###
GET{{moistSensServer_HostAddress}}/get-sensor-descriptions?description=carrots
Accept: application/json

