@moistSensServer_HostAddress = http://localhost:5298

GET {{moistSensServer_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{moistSensServer_HostAddress}}/humidity-post/
Content-Type: application/json

{
  "sensorName": "sensor1",
  "humidity": 51
}

###
GET {{moistSensServer_HostAddress}}/humidity-get/
Accept: application/json